### ISSUE TITLE
Error: ITMS-90668 Invalid Bundle Executable. Framework contains incomplete bitcode

### ISSUE THREAD

**Issue by n1schal** [TheEightBot/Xamarin.IQKeyboardManager#9] opened 2017-05-02 05:45 UTC
Getting this error when trying to push a build to TestFlight since the 1.2 update.

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'HHA.iOS.app/Frameworks/IQKeyboardManager.framework/IQKeyboardManager' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

Previously, I could add builds just fine but now even if I go back to 1.1, Application Loader raises this issue.

Any help? Need to upload a build ASAP

**Comment by michaelstonis** [comment] 2017-05-02 12:57
Hm, I am not sure exactly what to do here about this. I don't see anything that jumps out from the library configuration though. Can you try building the application using LLVM (https://developer.xamarin.com/guides/ios/advanced_topics/compiling_for_different_devices/) when you are doing an AD Hoc or Release Build?

**Comment by n1schal** [comment] 2017-05-08 05:09
Sorry for the late response. I'm kinda occupied with other stuff at the moment so will try this later on. Thanks for the help!

**Comment by n1schal** [comment] 2017-05-16 07:16
So I tried building using LLVM, it still gives me the same error when uploading to iTunesConnect.

Funny thing is, I did manage to get a build uploaded without LLVM once without any errors of the nature, and now when using the same build settings, I am getting the same error again.

**Comment by n1schal** [comment] 2017-05-18 17:01
@michaelstonis I was thinking of including the Xamarin.IQKeyboardManager project in my project as I can not get any builds to TestFlight. How do I use it if I do so? Tried referencing the project and then kept the same code, but I get a null expection.

**Comment by luigisaggese** [comment] 2017-05-24 11:34
I have same issue, 
ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'JRUITouch.app/Frameworks/IQKeyboardManager.framework/IQKeyboardManager' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

Someone have solved it?

**Comment by n1schal** [comment] 2017-05-24 11:37
@luigisaggese I think 1.2 was built with bitcode enabled or something, because no matter what I tried, I kept getting the same error.

For me, I went back to 1.1, Cleaned project, Rebuild project, and then archived for publishing. If there isn't a specific new feature you're looking to use from 1.2, I'd suggest you go back to 1.1 and then clean, rebuild and archive. HTH!

**Comment by luigisaggese** [comment] 2017-05-24 11:38
@n1schal I will do in that way (downgrade to 1.1) thanks.

**Comment by spaddlewit** [comment] 2017-06-17 13:38
@michaelstonis This was an issue with the original IQKeyboardManager adding some of Apple's private APIs. They've since fixed the issue, but this Xamarin binding needs to be updated. Maybe it's time for a 1.3? :)

**Comment by jkapsouras** [comment] 2017-06-26 06:37
Same problem here. Downgrade did not solve the problem. We had to remove the package. Waiting for solution with update!

**Comment by n1schal** [comment] 2017-06-26 06:39
@jkapsouras you need to clean and rebuild project after downgrading. it worked for me.

**Comment by jkapsouras** [comment] 2017-06-26 06:52
@n1schal we tried that, Xcode validated the archive but it failed to upload

**Comment by n1schal** [comment] 2017-06-26 07:03
@jkapsouras hmmm.. i had problems too initially but that's how i solved it. try removing it altogether, clean, rebuild, add and then clean and rebuild.

anyways, looks like we need a 1.3 soon with a fix for the issue @michaelstonis

**Comment by jkapsouras** [comment] 2017-06-26 08:30
@n1schal we will try once more. The problem is that the problem occurs in uploading and not in archiving and we cannot upload new versions only for checking this issue. Let's hope that the 1.3 version will be available soon! @michaelstonis

**Comment by n1schal** [comment] 2017-06-26 08:33
@jkapsouras i know. i had my builds failing to upload through Application Uploader as well but it was fixed by the steps I said

**Comment by spaddlewit** [comment] 2017-06-26 11:16
@n1schal , @jkapsouras I came up with a solution.
1) Download the official IQKeyboardManager code
2) Compile it yourself in XCode, and add a flag to force bitcode:
**Force usage of the flag by adding Other C Flags with OTHER_CFLAGS="-fembed-bitcode". Your xcodebuild invocation would look something like xcodebuild OTHER_CFLAGS="-fembed-bitcode" -target LookbackSDK build.** 
(See http://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled )

3) Download the Xamarin.IQKeyboardManager code, replace the .framework file with the one you generated in XCode, open up the project in Xamarin Studio, and compile it

4) This solution will not run on the iOS Simulator, but it WILL work on device!

**Comment by facundoplagash** [comment] 2017-06-26 19:55
I have the same problem with new version 1.3.

Any solution?

**Comment by michaelstonis** [comment] 2017-06-26 20:10
Have you tried doing a full clean and rebuild of the entire solution? The latest version is pointed against 4.0.10 and has the additional `OTHER_CFLAGS="-fembed-bitcode"` as suggested by @spaddlewit

**Comment by facundoplagash** [comment] 2017-06-26 21:33
Sorry, Clean & Remove obj/bin and now it's working.

Thank you!

**Comment by michaelstonis** [comment] 2017-06-26 21:41
Release 1.3 should resolve any issues with bitcode settings. If you are still experiencing this issue after upgrading, do a full clean and rebuild or _better yet_ delete all bin and obj folders in your solution.

**Comment by facundoplagash** [comment] 2017-06-27 02:55
@michaelstonis the issue persists in the new version.

Compiling my own framework version with ENABLE BITCODE = NO (like @spaddlewit says) works for Apple Store upload. BUT fails with simulator (.Shareinstance = NULL issue)

**Comment by michaelstonis** [comment] 2017-06-27 03:52
I may have found another flag to remove the bitcode bits with the information here: https://stackoverflow.com/questions/37613550/xcode-error-itms-90635-invalid-mach-o-in-bundle-submitting-to-app-store/37624641#37624641. I verified that LLVM was removed using this guide: https://stackoverflow.com/questions/37613550/xcode-error-itms-90635-invalid-mach-o-in-bundle-submitting-to-app-store/37624641#37624641

I stripped the bitcode using the `xcrun bitcode_strip` command and verfied using `otool`. Looks good, so I pushed version 1.3.1. If you are still experiencing this issue, please try a clean and rebuild or a full deletion of the bin/obj folders. If that still doesn't work try fire or silver bullet.

**Comment by facundoplagash** [comment] 2017-06-27 05:11
@michaelstonis I solved the problem using this config in .csproj with version 1.3

```
<Target Name="BeforeCodesign">
    <Exec  Condition=" '%(_Frameworks.FullPath)'!='' " Command="$(_SdkDevPath)\Toolchains\XcodeDefault.xctoolchain\usr\bin\bitcode_strip &quot;%(_Frameworks.FullPath)&quot; -r -o &quot;%(_Frameworks.FullPath)&quot;" />
  </Target>
```

It seems to be the same solution that you use in v 1.3.1 but in the library code side.

I'll try this new version and comment you the result.

Thank you!

**Comment by jkapsouras** [comment] 2017-06-27 06:13
@michaelstonis we will try the new version and post the results.

**Comment by michaelstonis** [comment] 2017-06-29 15:46
@jkapsouras or @n1schal any luck with the new package?

**Comment by jkapsouras** [comment] 2017-07-01 15:09
unfortunately have not try it yet. I will inform as soon as I upload to apple

**Comment by n1schal** [comment] 2017-07-03 05:32
@michaelstonis sorry, haven't had the need to upload a new build yet. I'll try and see if it gets to the upload screen, if it does, we can close this issue once and for all :)

**Comment by brenaud** [comment] 2017-07-03 16:47
version 1.3.1 did not fix the issue for me
However adding the config suggested by facundoplagash worked

**Comment by jkapsouras** [comment] 2017-07-04 13:44
Unfortunately no luck (neither with 1.3.1, nor with @brenaud )

**Comment by michaelstonis** [comment] 2017-07-04 17:05
@jkapsouras or @brenaud did you do a full clean and rebuild after you upgraded to 1.3.1? There is a pretty good chance that the last release was still cached.

**Comment by jkapsouras** [comment] 2017-07-04 17:15
Yes I did. Made various tests. Both with versions 1.3 and 1.3.1. Bin and obj folders deleted. Csproj changed according to @brenaud solution with no luck. All ipas were cut out during verifying assets on itunes

**Comment by brenaud** [comment] 2017-07-04 17:47
I tried a clean & build, I also tried to uninstall the package and then reinstalling it, got to error when trying to upload the ipa in both cases

But adding 

```
<Target Name="BeforeCodesign">
    <Exec  Condition=" '%(_Frameworks.FullPath)'!='' " Command="$(_SdkDevPath)\Toolchains\XcodeDefault.xctoolchain\usr\bin\bitcode_strip &quot;%(_Frameworks.FullPath)&quot; -r -o &quot;%(_Frameworks.FullPath)&quot;" />
</Target>
```

in the .csproj (in the second to last line, right before the closing </project> tag) with version 1.3.1 fixed everything for me

**Comment by michaelstonis** [comment] 2017-07-04 22:48
I just released version 1.3.2 which includes the new `BeforeCodesign` call. I am not exactly what is different about this and what I had applied earlier though. Let me know if you hit this issue with the latest @jkapsouras and @brenaud.

**Comment by jkapsouras** [comment] 2017-07-05 06:13
On the next version update, I will inform you. The problem is that you have to upload to check if the problem is solved.

**Comment by jkapsouras** [comment] 2017-07-05 13:52
Good news @michaelstonis ! The 1.3.2 version worked like a charm. We started a new project today, so I added the keyboard package and the ipa was successfully uploaded to iTunes. Thumbs up for a great package!

**Closed as completed** 2017-07-05 15:03 UTC
